targets:
  $default:
    builders:
      json_serializable:
        options:
          create_to_json: true
          explicit_to_json: true
          field_rename: "snake"
      chopper_generator:
        options:
          build_extensions: { ".dart": [ ".chopper.g.dart" ] }
