name: paperless
description: "A mobile client for paperless-ng*x."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.8
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter_gen:
  output: lib/core/gen

  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
